version: "2"
plugins:
  sonar-java:
    enabled: true
    config:
      tests_patterns:
        - app/src/test/**
        - app/src/testFull/**
        - app/src/testShared/**
        - app/src/androidTest/**
  pmd:
    enabled: true
    config:
      file: config/pmd/rules.xml